name: Salesforce CI with Selenium Tests

#on:
#  push:
#    branches:
#      #- feature/your-branch-name  # Specify the branch you want to checkout from
#      - master

on:
  workflow_dispatch:

jobs:
  test-salesforce-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository master
      uses: actions/checkout@v3
      with:
        #ref: feature/testBranch  # Specify your branch name here
        ref: master  # Specify your branch name here

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r tests/requirements.txt

  #install Salesforce CLI
    - name: Install Salesforce CLI
      run: |
        npm install -g sfdx-cli

    - name: Print UserName
      env:
        SALESFORCE_CONSUMER_KEY: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
        SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
        SALESFORCE_SERVER_KEY: ${{ secrets.SALESFORCE_SERVER_KEY1 }}
        # Ensure to add SALESFORCE_CONSUMER_KEY, SALESFORCE_USERNAME, and the server.key to your repository's secrets.
      run: | 
        echo "UserName is $SALESFORCE_USERNAME"

    - name: Create Server Key File
      run: |
          echo "${{ secrets.SALESFORCE_SERVER_KEY1 }}" > server.key
          sed -i 's/\\n/\n/g' server.key
          echo "${{ secrets.SALESFORCE_USERNAME }}"

    - name: Authenticate with Salesforce org
      env:
        SALESFORCE_CONSUMER_KEY: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
        SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
        SALESFORCE_SERVER_KEY: ${{ secrets.SALESFORCE_SERVER_KEY1 }}
        # Ensure to add SALESFORCE_CONSUMER_KEY, SALESFORCE_USERNAME, and the server.key to your repository's secrets.
      run: |
        sfdx auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername
      

    - name: Create Scratch Org
      run: |
        sfdx force:org:create -f config/project-scratch-def.json -d 7 -a ci-scratch-org

    - name: Push Source to Scratch Org
      run: |
        sfdx force:source:push -u ci-scratch-org

    - name: Run Apex Tests excluding Managed Package Tests
      run: |
        sfdx force:apex:test:run -u ci-scratch-org --testlevel RunLocalTests --codecoverage --resultformat json --outputdir ./apex-test-results
        ls -al ./apex-test-results
    - name: Run Selenium Tests
      run: |
        source venv/bin/activate
        pwd
        ls -al
        python tests/selenium/test_test1.py --resultfile selenium-test-results.json
        ls -al

    
  #send email 
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        # Server settings
        server_address: smtp.mail.yahoo.com
        server_port: 465
        
        secure: true
        ignore_cert: true
        convert_markdown: true
        priority: low
        # User settings
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        
        # Email settings
        subject: Salesforce Test Results
        # List of emails to send to:
        to: ${{ github.event.pusher.email }}
        # From which email to send:
        from: Alok Mishra alokmishrakolkata@gmail.com

        # Mail body
        body: Here are the Salesforce and Selenium test results attached.
        
        # File attachments
        attachments: 'apex-test-results/test-result.csv,selenium-test-results.csv'