name: Salesforce CI with Selenium Tests

on:
  push:
    branches:
      #- feature/your-branch-name  # Specify the branch you want to checkout from
      - master

jobs:
  test-salesforce-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository master
      uses: actions/checkout@v3
      with:
        #ref: feature/testBranch  # Specify your branch name here
        ref: master  # Specify your branch name here

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r tests/requirements.txt

    - name: Install Salesforce CLI
      run: |
        npm install -g sfdx-cli

    - name: Create Server Key File
      run: |
        echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        chmod 600 server.key

    - name: Authenticate with Salesforce
      run: |
        sfdx auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile ${{ secret.SALESFORCE_SERVER_KEY }} --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername
      env:
        SALESFORCE_CONSUMER_KEY: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
        SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
        SALESFORCE_SERVER_KEY: ${{ secrets.SALESFORCE_SERVER_KEY }}
        # Ensure to add SALESFORCE_CONSUMER_KEY, SALESFORCE_USERNAME, and the server.key to your repository's secrets.

    - name: Create Scratch Org
      run: |
        sfdx force:org:create -f config/project-scratch-def.json -s -d 7 -a ci-scratch-org

    - name: Push Source to Scratch Org
      run: |
        sfdx force:source:push -u ci-scratch-org

    - name: Run Selenium Tests
      run: |
        source venv/bin/activate
        python path/to/your_selenium_script.py

    - name: Run Apex Tests excluding Managed Package Tests
      run: |
        sfdx force:apex:test:run -u ci-scratch-org --testlevel RunLocalTests --codecoverage
