name: Salesforce CI with Selenium Tests

on:
  workflow_dispatch:

jobs:
  test-salesforce-app:
    runs-on: ubuntu-latest

    steps:
    - name: Send Email
      uses: hilarion5/send-mail@v1
      with:
        smtp-server: smtp.example.com
        smtp-port: 465
        smtp-secure: true
        from-email: alokmishrakolkata@gmail.com
        to-email: alokmishrajaipur@yahoo.com
        # User settings
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Test Email
        body: This is a test email sent from GitHub Actions.
        html: |
          <h1>This is a test email</h1>
          <p>Test Paragraph</p>