name: SendEmailTest

on:
  workflow_dispatch:

jobs:
  test-salesforce-app:
    runs-on: ubuntu-latest


    steps:
    # Step to create a file
    - name: Create a text file
      run: |
        echo "Hello, this is a test file." > testfile.txt
        ls -al


    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.mail.yahoo.com
        server_port: 465
        secure: true
        ignore_cert: true
        convert_markdown: true
        priority: low
        # User settings
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: alokmishrajaipur@yahoo.com
        to: alokmishrakolkata@gmail.com
        subject: Test Email
        html_body: This is a test email sent from GitHub Actions.
        attachments: testfile.txt